task_name: "glue_sst2"
task_type: "SEQ_CLS"

model:
  name_or_path: "meta-llama/Llama-3.2-1B"
  trust_remote_code: true

peft:
  method: "lora"
  lora_r: 16
  lora_alpha: 32
  lora_dropout: 0.05
  target_modules: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj","up_proj","down_proj"]
  bias: "none"
  task_type: "SEQ_CLS"
  init_lora_weights: pissa # default: gaussian 
  use_dora: false
  use_qalora: false
  use_rslora: false

loraga:
  batch_size: 32
  num_samples: 1024
  gradient:
    quant_flag: false
    save_path: data_cache/gradients

trainer:
  name: "SpectralRefactorTrainer"  # "SpectralRefactorTrainer"   # 使用自定义 Trainer 以支持多输入
  refactor_every: 100
  warmup_steps: 0
  balance_lambda: 0.8
  preserve_momentum: true
  clear_momentum: false
  damping_eps: 1e-5

# Dataset Configuration
dataset:
  name: "glue"
  subset: "sst2"  # Stanford Sentiment Treebank
  train_split: "train"
  eval_split: "validation"
  test_split: "test"
  text_column: ["sentence"]  # SST-2 has single sentence input
  label_column: "label"
  num_labels: 2  # Binary classification: positive (1) or negative (0)
  max_length: 128
  preprocessing_num_workers: 4

training:
  output_dir: "./outputs/glue_qnli_smol/SpectralRefactor"
  num_train_epochs: 5
  per_device_train_batch_size: 32
  per_device_eval_batch_size: 32
  gradient_accumulation_steps: 1       # 8 GPU => global_batch=128
  learning_rate: 0.0002               # 1e-4~2e-4 之间较稳
  weight_decay: 0.01
  warmup_ratio: 0.03
  lr_scheduler_type: "cosine"

  # Evaluation
  total_eval_times: 30
  load_best_model_at_end: true
  metric_for_best_model: "accuracy"
  greater_is_better: true
  save_total_limit: 3
  #early_stopping_patience: 3            # 需在 callback 中启用

  fp16: false
  bf16: true
  gradient_checkpointing: false
  optim: "adamw_torch"
  max_grad_norm: 1.0

  logging_steps: 100
  logging_dir: "./outputs/glue_qnli_smol/logs"
  report_to: ["wandb"]

wandb:
  project: "Llama-3.2-1B_GULE"
  run_name_suffix: "qalora"
  online: true