task_name: "glue_mnli"
task_type: "SEQ_CLS"

model:
  name_or_path: "HuggingFaceTB/SmolLM2-135M"
  trust_remote_code: true

peft:
  method: "lora"
  lora_r: 8
  lora_alpha: 16
  lora_dropout: 0.1
  #target_modules: 'all-linear'
  bias: "none"
  task_type: "SEQ_CLS"
  init_lora_weights: "gaussian" # default: gaussian 
  use_dora: false
  use_qalora: false
  use_rslora: false

loraga:
  batch_size: 32
  num_samples: 1024
  gradient:
    quant_flag: false
    save_path: data_cache/gradients

trainer:
  name: "Trainer"  # "SpectralRefactorTrainer"   # 使用自定义 Trainer 以支持多输入
  refactor_every: 100
  warmup_steps: 0
  balance_lambda: 0.8
  preserve_momentum: true
  clear_momentum: false
  damping_eps: 1e-5

# Dataset Configuration
dataset:
  name: "glue"
  subset: "mnli"
  train_split: "train"
  eval_split: "validation_matched"       # MNLI 主验证集 (matched)
  test_split: "test_matched"
  # MNLI 还有 validation_mismatched 和 test_mismatched
  text_column: ["premise", "hypothesis"]  # MNLI 的句对字段
  label_column: "label"
  num_labels: 3                           # MNLI 是三分类: entailment, neutral, contradiction
  max_length: 256
  preprocessing_num_workers: 4

training:
  output_dir: "./outputs/glue_mnli_smol"
  num_train_epochs: 3
  per_device_train_batch_size: 32
  per_device_eval_batch_size: 32
  gradient_accumulation_steps: 1       # 8 GPU => global_batch=128
  learning_rate: 0.0002               # 1e-4~2e-4 之间较稳
  weight_decay: 0.01
  warmup_ratio: 0.03
  lr_scheduler_type: "cosine"

  # Evaluation
  total_eval_times: 30
  load_best_model_at_end: true
  metric_for_best_model: "accuracy"
  greater_is_better: true
  save_total_limit: 3
  #early_stopping_patience: 3            # 需在 callback 中启用

  fp16: false
  bf16: true
  gradient_checkpointing: false
  optim: "adamw_torch"
  max_grad_norm: 1.0

  logging_steps: 100
  logging_dir: "./outputs/glue_mnli_smol/logs"
  report_to: ["wandb"]

wandb:
  project: "SmolLM2-135M-GLUE2"
  run_name_suffix: "base"
  online: true
