task_name: "glue_qnli"
task_type: "SEQ_CLS"

model:
  name_or_path: "HuggingFaceTB/SmolLM2-135M"
  trust_remote_code: true

peft:
  method: "lora"
  lora_r: 8
  lora_alpha: 16
  lora_dropout: 0.1
  #target_modules: 'all-linear'
  bias: "none"
  task_type: "SEQ_CLS"
  init_lora_weights: lora_ga # gaussian # default: gaussian 

loraga:
  batch_size: 32
  num_samples: 1024
  gradient:
    quant_flag: false
    save_path: data_cache/gradients

trainer:
  name: "Trainer"   # 使用自定义 Trainer 以支持多输入

dataset:
  name: "glue"
  subset: "qnli"
  train_split: "train"
  eval_split: "validation"
  test_split: "test"
  text_column: ["question", "sentence"]   # 关键修复：句对
  label_column: "label"
  num_labels: 2
  max_length: 256
  preprocessing_num_workers: 4

training:
  output_dir: "./outputs/glue_qnli_smol"
  num_train_epochs: 5
  per_device_train_batch_size: 32
  per_device_eval_batch_size: 32
  gradient_accumulation_steps: 1       # 8 GPU => global_batch=128
  learning_rate: 0.0002               # 1e-4~2e-4 之间较稳
  weight_decay: 0.0
  warmup_ratio: 0.0
  lr_scheduler_type: "cosine"

  # Evaluation
  total_eval_times: 50
  load_best_model_at_end: true
  metric_for_best_model: "accuracy"
  greater_is_better: true
  save_total_limit: 3
  #early_stopping_patience: 3            # 需在 callback 中启用

  fp16: false
  bf16: true
  gradient_checkpointing: false
  optim: "adamw_torch"
  max_grad_norm: 1.0

  logging_steps: 100
  logging_dir: "./outputs/glue_qnli_qwen/logs"
  report_to: ["wandb"]

wandb:
  project: "lora-go"
  run_name_suffix: "qnli_baseline"
  online: true